FROM alpine:latest
ENV KUBECONFIG /home/kubectl/.kube/kubeconfig
ENV HOME /home/kubectl
RUN \
    mkdir /root/bin /aws; \
    apk -Uuv add groff less bash python py-pip jq curl && \
    pip install --upgrade pip; \
    pip install awscli && \
    apk --purge -v del py-pip && \
    rm /var/cache/apk/* && \
    #Create non-root user (with a randomly chosen UID/GUI).
    adduser kubectl -Du 5566
ADD https://amazon-eks.s3.us-west-2.amazonaws.com/1.14.9/2020-07-08/bin/linux/amd64/kubectl /usr/local/bin/kubectl
#COPY kubectl /usr/local/bin/kubectl
WORKDIR $HOME
RUN chmod a+x /usr/local/bin/kubectl

#USER kubectl
ENTRYPOINT [""]